### ISSUE TITLE
add graphql api client

### ISSUE THREAD

**Issue by aramisromero89** [aramisromero89/flutter_todo_app#1]
### Tasks

- [x] add graphql fragments and operations
- [x] configure code generation
- [x] add api client helper
- [x] add api call wrapper
