### ISSUE TITLE
add graphql api client

### ISSUE THREAD

**Issue by aramisromero89** [aramisromero89/flutter_todo_app#1]
### Tasks
- [ ] add graphql operations
- [ ] configure code generation
- [ ] configure gql link
- [ ] add api call wrapper for normalizing response
